from __future__ import annotations

import json
import os
import re
from datetime import datetime
from pathlib import Path
from typing import Any
from uuid import uuid4

PROGRESS_RE = re.compile(r"^\[(\d+)/(\d+)\] (PASS|FAIL|ERROR)\b")


def parse_progress_line(line: str) -> tuple[int, int, str] | None:
    """Parse a ``[done/total] STATUS ...`` progress line printed by the harness.

    Returns ``(done, total, status)`` or ``None`` when the line is not a progress line.
    """
    match = PROGRESS_RE.match(line.strip())
    if match is None:
        return None
    return int(match.group(1)), int(match.group(2)), match.group(3)


def summarize(results: list[Any]) -> dict[str, Any]:
    total = len(results)
    passed = sum(1 for result in results if result.grade.passed)
    failed = total - passed
    errors = sum(1 for result in results if result.error)

    by_category: dict[str, dict[str, int]] = {}
    for result in results:
        category = result.category or "general"
        stats = by_category.setdefault(category, {"total": 0, "passed": 0, "failed": 0})
        stats["total"] += 1
        if result.grade.passed:
            stats["passed"] += 1
        else:
            stats["failed"] += 1

    average_score = sum(result.grade.score for result in results) / total if total else 0.0
    return {
        "total": total,
        "passed": passed,
        "failed": failed,
        "errors": errors,
        "average_score": round(average_score, 2),
        "by_category": by_category,
    }


def format_results(results: list[Any], *, complete: bool = True) -> str:
    if not results:
        return "No test cases were run."

    summary = summarize(results)
    lines = []
    if not complete:
        lines.append("PARTIAL RUN (interrupted or still running)")
    lines.extend(
        [
            f"Total: {summary['total']}",
            f"Passed: {summary['passed']}",
            f"Failed: {summary['failed']}",
            f"Errors: {summary['errors']}",
            f"Average score: {summary['average_score']}",
            "",
        ]
    )

    for result in results:
        status = "PASS" if result.grade.passed else "FAIL"
        transcript = result.transcript or "no transcript"
        duration = getattr(result, "duration_seconds", 0)
        lines.append(
            f"{status} [{result.category}] {result.case_id}: score {result.grade.score} "
            f"({duration:.1f}s) - {transcript}"
        )
        if result.grade.notes:
            lines.append(f"  notes: {result.grade.notes}")
        if result.error:
            lines.append(f"  error: {result.error}")

    return "\n".join(lines)


def format_failure_report(results: list[Any], *, complete: bool = True) -> str:
    """Return a deterministic Markdown snapshot containing only failed cases."""
    summary = summarize(results)
    failures = [result for result in results if not result.grade.passed]
    lines = [
        "# VoxaTest Failure Report",
        "",
        "<!-- Generated by VoxaTest. Re-run the harness instead of editing by hand. -->",
        "",
    ]
    if not complete:
        lines.append("- Status: partial run")
    lines.extend(
        [
            f"- Cases run: {summary['total']}",
            f"- Passed: {summary['passed']}",
            f"- Failed: {summary['failed']}",
            f"- Runtime errors: {summary['errors']}",
            "",
        ]
    )

    if not failures:
        lines.append("No failures were reported in the latest run.")
        return "\n".join(lines)

    for result in failures:
        lines.extend(
            [
                f"## {result.case_id}",
                "",
                f"- Category: `{result.category or 'general'}`",
                f"- Score: {result.grade.score}",
                f"- Grading method: `{result.grade.method}`",
                "",
                "### Prompt",
                "",
                _markdown_quote(result.prompt),
                "",
                "### Voxa response",
                "",
                _markdown_quote(result.transcript or "(no transcript)"),
                "",
                "### Failure notes",
                "",
                _markdown_quote(result.grade.notes or "(none)"),
            ]
        )
        if result.error:
            lines.extend(["", "### Runtime error", "", _markdown_quote(result.error)])
        lines.append("")

    return "\n".join(lines).rstrip()


def write_failure_report(results: list[Any], path: Path, *, complete: bool = True) -> Path:
    """Atomically replace the Git-friendly latest-failures snapshot."""
    return _atomic_write_text(Path(path), format_failure_report(results, complete=complete) + "\n")


def _markdown_quote(value: Any) -> str:
    text = str(value).replace("\r\n", "\n").replace("\r", "\n")
    return "\n".join(f"> {line}" if line else ">" for line in text.split("\n"))


def _atomic_write_text(path: Path, text: str) -> Path:
    """Write text through a temporary file so readers never see a half-written report."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(f".{path.name}.{os.getpid()}.{uuid4().hex}.tmp")
    try:
        temporary.write_text(text, encoding="utf-8")
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)
    return path


def report_paths(
    reports_dir: Path,
    json_path: Path | None = None,
    text_path: Path | None = None,
) -> tuple[Path, Path]:
    """Resolve the JSON and text report paths for a run, defaulting to unique run-id names."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
    run_id = f"{timestamp}_{os.getpid()}_{uuid4().hex[:8]}"
    reports_dir = Path(reports_dir)
    reports_dir.mkdir(parents=True, exist_ok=True)

    if json_path is None:
        json_path = reports_dir / f"run_{run_id}.json"
    if text_path is None:
        text_path = reports_dir / f"run_{run_id}.txt"

    return Path(json_path), Path(text_path)


def write_reports(
    results: list[Any],
    reports_dir: Path,
    *,
    json_path: Path | None = None,
    text_path: Path | None = None,
    failure_path: Path | None = None,
    complete: bool = True,
) -> dict[str, Any]:
    json_path, text_path = report_paths(reports_dir, json_path=json_path, text_path=text_path)

    payload = {
        "timestamp": datetime.now().isoformat(),
        "complete": complete,
        "summary": summarize(results),
        "results": [result.to_dict() for result in results],
    }
    _atomic_write_text(json_path, json.dumps(payload, indent=2, ensure_ascii=False) + "\n")
    _atomic_write_text(text_path, format_results(results, complete=complete) + "\n")
    if failure_path is not None:
        failure_path = write_failure_report(results, failure_path, complete=complete)

    return {
        "json_path": json_path,
        "text_path": text_path,
        "failure_path": failure_path,
        "summary": summarize(results),
    }
